title      = "Test Page"
site       = "https://www.example.com/"
articleDir = "test-data/content/"
themeDir   = "test-data/theme/"
outputDir  = "test-data/public/"
localServerPort  = 4000

[[menu]]
name = "Index"
loc  = "/"
