title = "Nutr1t07's Blog"
site = "https://nutr1t07.github.io/"
articleDir = "test-data/content/"
themeDir   = "test-data/theme/"
outputDir  = "test-data/public/"
localServerPort  = 4000

[[menu]]
name = "Index"
loc  = "/"

[[menu]]
name = "Friends"
loc  = "/page/friends/"
